version: '2'
services:
  spark-master:
    build: .
    ports:
      - "8080:8080"
      - "7077"
    command: /start-master.sh

  spark-slave-1:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER_HOST: spark-master
    command: /start-worker.sh

  spark-slave-2:
    build: .
    ports:
      - "8082:8081"
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER_HOST: spark-master
    command: /start-worker.sh
