version: '2'
services:
  spark_master:
    build: .
    ports:
      - "8080:8080"
      - "7077"
    command: /start-master.sh

  spark_slave_1:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPARK_MASTER_HOST: 172.19.0.2
    command: /start-worker.sh

  spark_slave_2:
    build: .
    ports:
      - "8082:8081"
    environment:
      SPARK_MASTER_HOST: 172.19.0.2
    command: /start-worker.sh
