version: '2'
services:
  spark_master:
    build: .
    ports:
      - "8080:8080"
      - "7077"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    command: /start-master.sh

  spark_slave_1:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPARK_MASTER_HOST: 172.18.0.2
    command: /start-worker.sh
